[deploy]
startCommand = "n8n start"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
[env]
N8N_LOG_LEVEL = "debug"
N8N_LOG_OUTPUT = "console"
